//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedTrailWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string City { get; set; }
        public string ZoneName { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
