//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedTrailMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedLocation
    {
        public RedLocation()
        {
            this.RedUsers = new HashSet<RedUser>();
        }
    
        public int Id { get; set; }
        public string City { get; set; }
        public string ZoneName { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string LongtitudeMedian { get; set; }
        public string LatitudeMedian { get; set; }
    
        public virtual ICollection<RedUser> RedUsers { get; set; }
    }
}
